# Generated by Django 4.0.4 on 2022-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='宿泊施設名称')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('tel', models.CharField(max_length=100, verbose_name='電話番号')),
                ('description', models.TextField(blank=True, default='', verbose_name='施設説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='施設イメージ画像')),
                ('spa', models.BooleanField(default=True)),
                ('highclass', models.BooleanField(default=True)),
                ('ido', models.FloatField(blank=True, default=0, null=True, verbose_name='')),
                ('keido', models.FloatField(blank=True, default=0, null=True, verbose_name='')),
            ],
        ),
    ]
