# Generated by Django 4.0.4 on 2022-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='ido',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='keido',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='経度'),
        ),
    ]
