# Generated by Django 4.0.4 on 2022-06-02 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_hotel_ido_alter_hotel_keido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='highclass',
            field=models.BooleanField(default=True, verbose_name='ハイクラスホテル'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='spa',
            field=models.BooleanField(default=True, verbose_name='温泉'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.IntegerField(verbose_name='部屋のタイプ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='部屋イメージ画像')),
                ('name', models.CharField(max_length=100, verbose_name='宿泊者氏名')),
                ('number_of_guest', models.IntegerField(verbose_name='宿泊人数')),
                ('roomcharge', models.IntegerField(verbose_name='金額')),
                ('no_smoking', models.BooleanField(default=True, verbose_name='禁煙ルーム')),
                ('outdoor_bath', models.BooleanField(default=True, verbose_name='露天風呂')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
            ],
        ),
    ]
