# Generated by Django 4.0.4 on 2022-06-03 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_hotel_highclass_alter_hotel_spa_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkindate', models.DateField(help_text='チェックイン日')),
                ('stay', models.IntegerField(verbose_name='泊数')),
                ('checkintime', models.TimeField(help_text='チェックイン予定時間')),
                ('number_of_rooms', models.IntegerField(verbose_name='部屋数')),
                ('number_of_guests', models.IntegerField(verbose_name='宿泊人数')),
                ('first_name', models.CharField(max_length=100, verbose_name='宿泊者氏名(姓)')),
                ('last_name', models.CharField(max_length=100, verbose_name='宿泊者氏名(名)')),
                ('first_name_kana', models.CharField(max_length=100, verbose_name='宿泊者氏名(姓カナ)')),
                ('last_name_kana', models.CharField(max_length=100, verbose_name='宿泊者氏名(名カナ)')),
                ('post', models.CharField(max_length=10, verbose_name='住所(郵便番号)')),
                ('prefecture', models.IntegerField(verbose_name='住所(都道府県)')),
                ('address', models.CharField(max_length=100, verbose_name='住所(市町村名・番地)')),
                ('tel', models.CharField(max_length=15, verbose_name='電話番号')),
                ('age', models.IntegerField(verbose_name='年代')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='その他備考欄')),
                ('stayplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel', verbose_name='宿泊プラン')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel', verbose_name='宿泊施設名称'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel', verbose_name='店舗')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=100, verbose_name='プラン名')),
                ('description', models.TextField(default='', verbose_name='プラン説明')),
                ('roomcharge', models.IntegerField(verbose_name='金額')),
                ('start_reception', models.DateField(help_text='受付開始日')),
                ('end_reception', models.DateField(help_text='受付終了日')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='部屋イメージ画像')),
                ('room', models.ManyToManyField(blank=True, to='app.booking')),
            ],
        ),
    ]
