# Generated by Django 4.0.4 on 2022-06-03 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking_alter_room_hotel_staff_bookingplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkindate',
            field=models.DateField(verbose_name='チェックイン日'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkintime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='チェックイン予定時間'),
        ),
        migrations.AlterField(
            model_name='bookingplan',
            name='room',
            field=models.ManyToManyField(blank=True, to='app.room'),
        ),
    ]
