# Generated by Django 4.0.4 on 2022-06-03 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_booking_checkindate_alter_booking_checkintime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkintime',
            field=models.TimeField(verbose_name='チェックイン予定時間'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stayplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookingplan', verbose_name='宿泊プラン'),
        ),
    ]
