# Generated by Django 4.0.4 on 2022-06-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_loginuser_alter_booking_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingplan',
            name='hotel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hotel'),
        ),
        migrations.AlterField(
            model_name='bookingplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='プランイメージ画像'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='部屋名'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.IntegerField(choices=[(1, 'シングル'), (2, 'ツイン'), (3, 'ダブル'), (4, 'キング')], verbose_name='部屋のタイプ'),
        ),
    ]
