# Generated by Django 4.0.4 on 2022-06-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookingplan_hotel_alter_bookingplan_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_amount',
            field=models.IntegerField(default=None, null=True, verbose_name='合計(税込)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomcharge',
            field=models.IntegerField(verbose_name='大人1名(税込)'),
        ),
    ]
