# Generated by Django 4.0.4 on 2022-06-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_room_total_amount_alter_room_roomcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingplan',
            name='total_amount',
            field=models.IntegerField(default=None, null=True, verbose_name='合計(税込)'),
        ),
        migrations.AlterField(
            model_name='bookingplan',
            name='roomcharge',
            field=models.IntegerField(verbose_name='大人1名(税込)'),
        ),
    ]
