# Generated by Django 4.0.4 on 2022-06-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bookingplan_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingplan',
            name='checkin',
            field=models.TimeField(default='15:00', verbose_name='チェックイン'),
        ),
        migrations.AddField(
            model_name='bookingplan',
            name='checkout',
            field=models.TimeField(default='11:00', verbose_name='チェックアウト'),
        ),
        migrations.AddField(
            model_name='bookingplan',
            name='meal',
            field=models.IntegerField(choices=[(1, '食事なし'), (2, '朝のみ'), (3, '朝・夕')], default=1, verbose_name='食事'),
        ),
        migrations.AddField(
            model_name='bookingplan',
            name='short_description',
            field=models.TextField(default='', verbose_name='プラン概要'),
        ),
    ]
